### ISSUE TITLE
TypeError: Cannot read property 'queue' of undefined

### ISSUE THREAD

**Issue by cryptix** [ssbc/ssb-db#248]
```
/home/cryptix/scuttle-shell/node_modules/ssb-db/minimal.js:220
    const isEmptyInactiveQueue = !queue.buffer.queue.length && !queue.writing
                                               ^

TypeError: Cannot read property 'queue' of undefined
    at EventEmitter.db.flush (/home/cryptix/scuttle-shell/node_modules/ssb-db/minimal.js:220:48)
    at /home/cryptix/scuttle-shell/node_modules/ssb-db/index.js:129:12
    at /home/cryptix/scuttle-shell/node_modules/pull-stream/sinks/drain.js:20:24
    at /home/cryptix/scuttle-shell/node_modules/pull-stream/throughs/async-map.js:28:19
    at /home/cryptix/scuttle-shell/node_modules/pull-stream/throughs/through.js:19:9
    at PacketStreamSubstream.weird.read (/home/cryptix/scuttle-shell/node_modules/muxrpc/pull-weird.js:33:7)
    at PacketStream._onstream (/home/cryptix/scuttle-shell/node_modules/packet-stream/index.js:200:12)
    at PacketStream.write (/home/cryptix/scuttle-shell/node_modules/packet-stream/index.js:135:41)
    at /home/cryptix/scuttle-shell/node_modules/muxrpc/pull-weird.js:56:15
    at /home/cryptix/scuttle-shell/node_modules/pull-stream/sinks/drain.js:24:37
```

```
scuttle-shell@0.1.3 /home/cryptix/scuttle-shell
└─┬ ssb-server@13.6.0
  └── ssb-db@18.6.4 
```

I changed line 222 to `!queue.buffer && !queue.writing` to have this not crash but I don't know how this is triggered yet.

**Comment by arj03** [comment]
The problem is this commit:

https://github.com/ssbc/ssb-db/commit/69274141ba61e53911f8723b7fbf66720895976a

There was a guard against !queue.buffer.

**Comment by dominictarr** [comment]
and now that guard is after the thing it should be guarding!
