### ISSUE TITLE
How to get flumedb sequence number for a message?

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-db#260]
I thought it would be something like `ssbDb.get({ key: '%...', seqs: true })` but that's throwing an error:
```
TypeError: Cannot read property '0' of undefined
    at Object.exports.isMsgLink (/home/christianbundy/src/ssbc/patchwork/node_modules/ssb-server/node_modules/ssb-ref/index.js:77:11)
    at EventEmitter.db.get (/home/christianbundy/src/ssbc/patchwork/node_modules/ssb-server/node_modules/ssb-db/create.js:65:20)
    at apply (/home/christianbundy/src/ssbc/patchwork/node_modules/ssb-server/node_modules/muxrpc-validation/index.js:197:15)
    at EventEmitter.<anonymous> (/home/christianbundy/src/ssbc/patchwork/node_modules/ssb-server/node_modules/muxrpc-validation/index.js:86:14)
    at EventEmitter.hooked [as get] (/home/christianbundy/src/ssbc/patchwork/node_modules/ssb-server/node_modules/hoox/index.js:10:15)
    at /home/christianbundy/src/ssbc/patchwork/sbot/index.js:217:13
    at Object.isBlocking (/home/christianbundy/src/ssbc/patchwork/sbot/contacts.js:70:9)
    at Array.ssb.addMap (/home/christianbundy/src/ssbc/patchwork/sbot/index.js:214:24)
    at next (/home/christianbundy/src/ssbc/patchwork/node_modules/ssb-server/node_modules/ssb-db/minimal.js:98:20)
    at Array.unboxerMap (/home/christianbundy/src/ssbc/patchwork/node_modules/ssb-server/node_modules/ssb-db/minimal.js:85:35)
```

Should I be doing something else? My goal is to get all flumedb sequence numbers for messages from a given author, but the first step is just getting the sequence number for a single message.

**Comment by christianbundy** [comment]
Oops, looks like the correct usage is `{ id }` rather than `{ keys }`, but that method doesn't seem to pass on any options so I'm unclear on how to get a flumedb sequence number for a message.
