### ISSUE TITLE
Incorrect get() documentation/buggy function

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-db#287]
[This section](https://github.com/ssbc/ssb-db#dbget-id--seq--opts-cb) says "If opts is passed, the message id is taken from either opts.id or opts.key" but when I test

```
        server.get({ id: rootKey, meta: true }, (err, rootMsg) => {
```
that works, but
```
        server.get({ key: rootKey, meta: true }, (err, rootMsg) => {
```
doesn't. I get this
```
/home/me/prj/ssb/ssb-wiki/node_modules/ssb-ref/index.js:77
  return s[0] === '%' && isLink(s)
          ^

TypeError: Cannot read property '0' of undefined
    at Object.exports.isMsgLink (/home/me/prj/ssb/ssb-wiki/node_modules/ssb-ref/index.js:77:11)
    at EventEmitter.db.get (/home/me/prj/ssb/ssb-wiki/node_modules/ssb-db/create.js:100:20)
    at apply (/home/me/prj/ssb/ssb-wiki/node_modules/muxrpc-validation/index.js:197:15)
    at EventEmitter.<anonymous> (/home/me/prj/ssb/ssb-wiki/node_modules/muxrpc-validation/index.js:86:14)
    at EventEmitter.hooked [as get] (/home/me/prj/ssb/ssb-wiki/node_modules/hoox/index.js:10:15)
    at /home/me/prj/ssb/ssb-wiki/index.js:77:16
    at /home/me/prj/ssb/ssb-wiki/node_modules/pull-stream/sinks/reduce.js:10:5
    at /home/me/prj/ssb/ssb-wiki/node_modules/pull-stream/sinks/drain.js:20:24
    at /home/me/prj/ssb/ssb-wiki/node_modules/pull-stream/throughs/through.js:19:9
    at /home/me/prj/ssb/ssb-wiki/node_modules/pull-stream/throughs/filter.js:17:11
```

If this is actually supposed to work, then when I skimmed the code it looked like this function came directly from flumedb so the bug might be there instead but I'm not sure.

**Comment by mixmix** [comment]
confirmed, I also recently got this behaviour :(

What do we want the actual behaviour to be?

**Comment by christianbundy** [comment]
> What do we want the actual behaviour to be?

I like 'id', but whatever the docs say is fine with me.

**Comment by mixmix** [comment]
I think being able to pay id or key in (but not both!) seems good

**Comment by christianbundy** [comment]
Sounds like we should just fix the docs then. :rocket:

**Comment by mixmix** [comment]
No what I meant was it should accept either ID OR Key but throw an error if
both are supplied!

**Comment by christianbundy** [comment]
(iIf you assign yourself ("I'm someone who wants this issue to stay open") then the bot will never touch it.)

**Comment by mixmix** [comment]
Keep this open please
