### ISSUE TITLE
Intermittent test failures on Windows (Travis CI)

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-db#300]
Most of the time Travis builds work great, but every few builds we have a failure on Windows that requires restarting the test. It's not a show-stopper, but it's likely indicative of a deeper problem.

**Comment by christianbundy** [comment]
Example:

```
not ok 241 Error [ERR_SERVER_NOT_RUNNING]: Server is not running.

  ---

    operator: error

    at: <anonymous> (C:\Users\travis\build\ssbc\ssb-db\node_modules\secret-stack\core.js:258:21)

    stack: |-

      Error [ERR_SERVER_NOT_RUNNING]: Server is not running.

          at Server.close (net.js:1602:12)

          at Object.onceWrapper (events.js:421:28)

          at Server.emit (events.js:315:20)

          at emitCloseNT (net.js:1655:8)

          at processTicksAndRejections (internal/process/task_queues.js:83:21)

  ...

not ok 242 plan != count

  ---

    operator: fail

    expected: 5

    actual:   6

    stack: |-

      Error: plan != count

          at Test.assert [as _assert] (C:\Users\travis\build\ssbc\ssb-db\node_modules\tape\lib\test.js:260:54)

          at Test.bound [as _assert] (C:\Users\travis\build\ssbc\ssb-db\node_modules\tape\lib\test.js:84:32)

          at Test.fail (C:\Users\travis\build\ssbc\ssb-db\node_modules\tape\lib\test.js:354:10)

          at Test.bound [as fail] (C:\Users\travis\build\ssbc\ssb-db\node_modules\tape\lib\test.js:84:32)

          at Test.assert [as _assert] (C:\Users\travis\build\ssbc\ssb-db\node_modules\tape\lib\test.js:346:14)

          at Test.bound [as _assert] (C:\Users\travis\build\ssbc\ssb-db\node_modules\tape\lib\test.js:84:32)

          at Test.error (C:\Users\travis\build\ssbc\ssb-db\node_modules\tape\lib\test.js:407:10)

          at Test.bound [as ifError] (C:\Users\travis\build\ssbc\ssb-db\node_modules\tape\lib\test.js:84:32)

          at Test.end (C:\Users\travis\build\ssbc\ssb-db\node_modules\tape\lib\test.js:173:14)

          at bound (C:\Users\travis\build\ssbc\ssb-db\node_modules\tape\lib\test.js:84:32)

  ...

Error [ERR_SERVER_NOT_RUNNING]: Server is not running.

    at Server.close (net.js:1602:12)

    at Object.onceWrapper (events.js:421:28)

    at Server.emit (events.js:315:20)

    at emitCloseNT (net.js:1655:8)

    at processTicksAndRejections (internal/process/task_queues.js:83:21) {

  code: 'ERR_SERVER_NOT_RUNNING'

}
```

**Comment by cryptix** [comment]
This feels like a race where sbot already closed for some reason before the tests do that? 

Running these a few hundred times should produce this but I don’t have a windows dev environment laying around right now.

**Comment by christianbundy** [comment]
Workaround I want to do but I'm not proud of: ignore `ERR_SERVER_NOT_RUNNING` in [this `if`](https://github.com/ssbc/ssb-db/blob/57af679a3fb099b48130b35cc46d1482b1ed08cd/index.js#L85).
